import type { Result } from "./api.js";
/**
 * Try catch wrapper for functions that can throw errors.
 *
 * @example
 *   const result = tryCatch(() => failingFunction())
 *   result.data
 *   result.error
 *
 *   const result = await tryCatch(() => asyncFailingFunction())
 */
export declare function tryCatch<Data>(callback: () => Promise<Data>): Promise<Result<Data, Error>>;
export declare function tryCatch<Data>(callback: () => Data): Result<Data, Error>;
//# sourceMappingURL=tryCatch.d.ts.map